[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'
lazy = 0
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/neomru.vim'
lazy = 0
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
lazy = 1
on_map = '<Plug>'
on_cmd = 'VimShell'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
lazy = 1
on_map = '<Plug>'
on_cmd = 'VimFiler'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
lazy = 1
on_i = 1
on_cmd = [
	'NeoSnippetEdit',
	'NeoSnippetClearMarkers',
	'NeoSnippetMakeCache',
	'NeoSnippetSource'
]

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
lazy = 1
on_source = 'neosnippet.vim'

[[plugins]]
repo = 'chriskempson/base16-vim'

[[plugins]]
repo = 'cespare/vim-toml'
lazy = 1
on_ft = 'toml'

[[plugins]]
repo = 'ledger/vim-ledger'
lazy = 1
on_ft = 'ledger'

[[plugins]]
repo = 'tpope/vim-fugitive'
lazy = 0
augroup = 'fugitive'
on_cmd = [
	'Gstatus',
	'Gdiff',
	'Gwrite',
	'Gread',
	'Gsplit',
	'Gvsplit',
	'Gtabedit',
	'Gcommit',
	'Gblame',
	'Gmove',
	'Gremove',
	'Ggrep',
	'Glog',
	'Gbrowse',
	'Git',
	'Git!',
]

[[plugins]]
repo = 'junegunn/vim-easy-align'
lazy = 1
on_cmd = ['EasyAlign', 'LiveEasyAlign']
on_map = '<Plug>(EasyAlign)'

[[plugins]]
repo = 'majutsushi/tagbar'
lazy = 1
augroup = 'TagbarSession'
on_cmd = [
	'Tagbar',
	'TagbarToggle',
	'TagbarOpen',
	'TagbarOpenAutoClose',
]

[[plugins]]
repo = 'Rip-Rip/clang_complete.git'
lazy = 1
on_ft = [
	'c',
	'cpp'
]

[[plugins]]
repo = 'neomake/neomake'
rev = 'master'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
lazy = 1
on_map = '<Plug>'

[[plugins]]
repo = 'ciaranm/securemodelines'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
lazy = 1
on_path = '\.coffee$'

[[plugins]]
repo = 'lervag/vimtex'
lazy = 1
on_ft = 'tex'

[[plugins]]
repo = 'rhysd/vim-crystal'
lazy = 1
on_path = '\.cr$'
on_ft = 'crystal'

[[plugins]]
repo = 'mxw/vim-jsx'
lazy = 1
on_ft = 'javascript'

[[plugins]]
repo = 'pangloss/vim-javascript'
lazy = 1
on_ft = 'javascript'

[[plugins]]
repo = 'tpope/vim-abolish'
lazy = 0

[[plugins]]
repo = 'tpope/vim-bundler'
lazy = 1
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
lazy = 1
on_ft = [
	'ruby',
	'haml',
	'erb'
]

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'aklt/vim-substitute'
lazy = 1
on_map = ';;'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
lazy = 1
on_map = [
	'gS',
	'gJ'
]

[[plugins]]
repo = 'Shougo/deoplete.nvim'
lazy = 1
on_i = 1
depends = [
	'nvim-yarp'
	'vim-hug-neovim-rpc'
]

[[plugins]]
repo = 'roxma/nvim-yarp'
lazy = 1

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
lazy = 1

[[plugins]]
repo = 'jimf/javascriptcomplete'
lazy = 1
on_ft = 'javascript'

[[plugins]]
repo = 'kmnk/vim-unite-giti'
lazy = 0
on_source = 'unite.vim'

[[plugins]]
repo = 'reedes/vim-lexical'
lazy = 1
augroup = 'lexical'
on_ft = ['tex', 'markdown', 'text', 'mail', 'text']

[[plugins]]
repo = 'vim-scripts/LanguageTool'
lazy = 1
on_cmd = 'LanguageToolCheck'

[[plugins]]
repo = 'tpope/vim-endwise'
lazy = 1
on_ft = [
	'ruby',
	'vim',
	'bash'
]

[[plugins]]
repo = 'chrisbra/NrrwRgn'
lazy = 1
on_cmd = 'NR'

[[plugins]]
repo = 'vim-scripts/FastFold'
lazy = 1 
on_i = 1

[[plugins]]
repo = 'kana/vim-operator-user'
lazy = 1
on_source = 'vim-operator-surround'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
lazy = 1
on_map = '<Plug>'

[[plugins]]
repo = 'jreinert/rbnew'
lazy = 1
on_cmd = 'Rbnew'

[[plugins]]
repo = 'romgrk/vimfiler-prompt'
lazy = 1
on_cmd = 'VimFilerPrompt'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'chiedo/vim-case-convert'
lazy = 1
on_cmd = [
	'CamelToHyphen',
	'CamelToSnake',
	'HyphenToCamel',
	'HyphenToSnake',
	'SnakeToCamel',
	'SnakeToHyphen',
	'CamelToHyphenAll',
	'CamelToSnakeAll',
	'HyphenToCamelAll',
	'HyphenToSnakeAll',
	'SnakeToCamelAll',
	'SnakeToHyphenAll',
	'CamelToHyphenAll!',
	'CamelToSnakeAll!',
	'HyphenToCamelAll!',
	'HyphenToSnakeAll!',
	'SnakeToCamelAll!',
	'SnakeToHyphenAll!',
]

[[plugins]]
repo = 'sirtaj/vim-openscad'
lazy = 1
on_ft = 'scad'

[[plugins]]
repo = 'junegunn/vader.vim'
lazy = 1
on_cmd = ['Vader', 'Vader!']

[[plugins]]
repo = 'elzr/vim-json'
lazy = 1
on_ft = 'json'

[[plugins]]
repo = 'puppetlabs/puppet-syntax-vim'
lazy = 1
on_ft = 'puppet'

[[plugins]]
repo = 'elorest/vim-slang'
lazy = 1
on_ft = 'slang'

[[plugins]]
repo = 'digitaltoad/vim-pug'
lazy = 1
on_ft = 'pug'

[[plugins]]
repo = 'https://gitlab.com/HiPhish/jinja.vim.git'
lazy = 1
on_ft = 'j2'

[[plugins]]
repo = 'leafgarland/typescript-vim'
lazy = 1
on_path = '\.(ts|vue)$'
on_ft = ['typescript','vue']

[[plugins]]
repo = 'posva/vim-vue'
lazy = 1
on_path = '\.vue$'
on_ft = 'vue'

[[plugins]]
repo = 'vim-scripts/DrawIt'
lazy = 1
on_map = [
	'<Leader>di'
]

[[plugins]]
repo = 'rhysd/devdocs.vim'
lazy = 1
on_cmd = ['DevDocs', 'DevDocsAll']
on_map = { n = 'K' }

[[plugins]]
repo = 'jparise/vim-graphql'
on_path = '\.g(raph)?qls?'
on_ft = 'graphql'
